setw -g mode-keys vi
set-option -g set-clipboard on

set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:RGB"

set -g mouse on
set -g history-limit 50000

bind -n WheelUpPane if-shell -F -t= "#{mouse_any_flag}" \
  "send-keys -M" \
  "if -F '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e; send-keys -M'"

bind -n WheelDownPane select-pane \; send-keys -M

bind -n MouseDown1Pane select-pane
bind -T copy-mode-vi MouseDrag1Pane select-pane \; send -X begin-selection
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-selection-and-cancel
